global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['server:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
